image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin'

before_script:
  - mkdir -p ~/.ssh
  - chmod 0600 ~/.ssh
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - terraform --version
  - mkdir ~/.aws
  - touch ~/.aws/credentials
  - echo $default > ~/.aws/credentials
  - echo $aws_access_key >> ~/.aws/credentials
  - echo $aws_secret_key >> ~/.aws/credentials
  - terraform init
  - uptime
  - df -h

after_script:
#  - mkdir -p /root/Devops-tools
#  - systemctl status nginx

stages:
  - validate
  - plan
  - plan2
  - apply
  - destroy
  - refresh

validate:
  stage: validate
  script:
    - terraform validate
  after_script:
    - echo "Successfuly Validated" 
    

plan:
  stage: plan
  script:
    - terraform plan
  after_script:
    - echo "Plan Successful" 
    
plan2:
  stage: plan
  script:
    - terraform plan
  after_script:
    - echo "Plan2 Successful"
    
apply:
  stage: apply
  script:
    - terraform  apply --auto-approve
  dependencies:
    - plan
  after_script:
    - echo "Successfully Applied" 
  when: always

destroy:
  stage: destroy
  script:
    - terraform  destroy --auto-approve
  dependencies:
    - plan
  after_script:
    - echo "Successfully Destroyed" 
  when: always
  
refresh:
  stage: destroy
  script:
    - terraform refresh
  dependencies:
    - plan
  after_script:
    - echo "Refresh Successful!!" 
  only:
  - destroy