image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin'

before_script:
  - mkdir -p ~/.ssh
  - chmod 0600 ~/.ssh
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - terraform --version
#  - mkdir ~/.aws
#  - touch ~/.aws/credentials
#  - echo $default > ~/.aws/credentials
#  - echo $aws_access_key >> ~/.aws/credentials
#  - echo $aws_secret_key >> ~/.aws/credentials
  - terraform init
  - uptime
  - df -h

after_script:
#  - mkdir -p /root/Devops-tools
#  - systemctl status nginx

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate
  script:    
    - terraform plan
  after_script:
    - echo "Successfuly Validated" 
    

plan:
  stage: validate
  script:
    - terraform validate
  script:    
    - terraform plan
  after_script:
    - echo "Plan Successfuly" 
    

apply:
  stage: apply
  script:
    - terraform  apply --auto-approve
  dependencies:
    - plan
  after_script:
    - echo "Successfuly Applied" 
  when: manual

destroy:
  stage: destroy
  script:
    - terraform  destroy --auto-approve
  dependencies:
    - plan
  after_script:
    - echo "Successfuly Destroyed" 
  when: manual
